language: java
mvn clean compile install -DskipTests=true -Dmaven.javadoc.skip=true
mvn test

jdk:
  - oraclejdk8

before_install:
  - echo 'before_install'

script:
  - mvn clean compile install -DskipTests=true -Dmaven.javadoc.skip=true
  - mvn test