language: java

jdk:
  - openjdk8

before_install:
  - echo 'before_install'

script:
  - mvn clean compile install -DskipTests=true -Dmaven.javadoc.skip=true
  - mvn test

after_script:
  - echo 'after_script'